name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

jobs:
  call-dockerhub-action:
    uses: NelsonDane/Custom-GitHub-Actions/.github/workflows/dockerhub-description.yml@e3876788a573bfb35bac32593c4075b87c37e774
    with:
      dockerhub_repo_name: auto-rsa
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
